name: cgv_clone_coding
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter

  fluttertoast: ^8.2.12
  optimized_cached_image: ^3.0.1
  video_player: ^2.9.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/